# Generated by Django 4.0.3 on 2022-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=150, verbose_name='Логотип')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('school', models.CharField(max_length=150, verbose_name='Школа')),
                ('objects_school', models.CharField(max_length=150, verbose_name='Предмет')),
                ('date', models.DateField(verbose_name='Дата')),
                ('biograf', models.TextField(verbose_name='Биография')),
                ('diploma', models.TextField(verbose_name='Дипломы')),
                ('education', models.CharField(max_length=150, verbose_name='Образование')),
                ('experience', models.CharField(max_length=150, verbose_name='Стаж работы')),
                ('qualif', models.CharField(max_length=150, verbose_name='Повышение квалификации')),
            ],
            options={
                'verbose_name': 'Портволио',
                'verbose_name_plural': 'Портволио',
            },
        ),
    ]
