# Generated by Django 4.0.3 on 2022-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenstar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='diploma',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma1',
            field=models.TextField(null=True, verbose_name='Дипломы1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma2',
            field=models.TextField(null=True, verbose_name='Дипломы2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma3',
            field=models.TextField(null=True, verbose_name='Дипломы3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma4',
            field=models.TextField(null=True, verbose_name='Дипломы4'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma5',
            field=models.TextField(null=True, verbose_name='Дипломы5'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma6',
            field=models.TextField(null=True, verbose_name='Дипломы6'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma7',
            field=models.TextField(null=True, verbose_name='Дипломы7'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='diploma8',
            field=models.TextField(null=True, verbose_name='Дипломы8'),
        ),
    ]
